version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html/app
    working_dir: /var/www/html/app
    tty: true
