name: PHP 7.4 Laravel Build

on:
  pull_request:
    branches:
      - master
      - staging
      - develop
      - feature/*
      - hotfix/*

jobs:
  runner:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]
    container: mathleite/php-composer

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: composer install

      - name: Run Test
        run: composer run-script test

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: mathleite/php-app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
