name: PHP 7.4 Laravel Build

on:
  pull_request:
    branches:
      - master
      - staging
      - develop
      - feature/*
      - hotfix/*

jobs:
  runner:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    container: mathleite/php-composer

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: composer install

      - name: Run Test
        run: composer run-script test

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: mathleite/php-app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile

  automerge:
    name: Merge Pull Request
    runs-on: [ubuntu-latest]
    needs: [runner]

    steps:
      - name: Merge
        uses: pascalgn/automerge-action@a4b03eff945989d41c623c2784d6602560b91e5b
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
