name: PHP 7.4 Test Runner

on: [push, pull_request]

jobs:
  runner:
    runs-on: ubuntu-latest
#    container: mathleite/php-composer:1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: composer run-script test
